apiVersion: batch/v1
kind: Job
metadata:
  name: backfill-loader
  namespace: default
spec:
  ttlSecondsAfterFinished: 86400  # 24시간 후 자동 삭제
  template:
    spec:
      containers:
      - name: backfill-loader
        image: backfill-loader:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: fms-config
              key: KAFKA_BROKERS
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: fms-config
              key: KAFKA_TOPIC
        - name: KAFKA_GROUP_ID
          value: "backfill-loader"
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: fms-config
              key: MINIO_ENDPOINT
        - name: MINIO_BUCKET
          valueFrom:
            configMapKeyRef:
              name: fms-config
              key: MINIO_BUCKET
        - name: MINIO_SECURE
          valueFrom:
            configMapKeyRef:
              name: fms-config
              key: MINIO_SECURE
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fms-secrets
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fms-secrets
              key: MINIO_SECRET_KEY
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
      restartPolicy: OnFailure
      backoffLimit: 3
