# 시간별 병합 - 매시 1분에 실행
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-merger-hour
  namespace: default
spec:
  schedule: "1 * * * *"  # 매시 1분
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-merger
            image: batch-merger:v1
            imagePullPolicy: IfNotPresent
            args: ["hour"]
            env:
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_ENDPOINT
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_BUCKET
            - name: MINIO_SECURE
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_SECURE
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fms-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fms-secrets
                  key: MINIO_SECRET_KEY
            resources:
              requests:
                memory: "512Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
          restartPolicy: OnFailure
---
# 일별 병합 - 매일 00시 5분에 실행
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-merger-day
  namespace: default
spec:
  schedule: "5 0 * * *"  # 매일 00시 5분
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-merger
            image: batch-merger:v1
            imagePullPolicy: IfNotPresent
            args: ["day"]
            env:
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_ENDPOINT
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_BUCKET
            - name: MINIO_SECURE
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_SECURE
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fms-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fms-secrets
                  key: MINIO_SECRET_KEY
            resources:
              requests:
                memory: "1Gi"
                cpu: "200m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
          restartPolicy: OnFailure
---
# 주별 병합 - 매주 월요일 00시 10분에 실행
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-merger-week
  namespace: default
spec:
  schedule: "10 0 * * 1"  # 매주 월요일 00시 10분
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-merger
            image: batch-merger:v1
            imagePullPolicy: IfNotPresent
            args: ["week"]
            env:
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_ENDPOINT
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_BUCKET
            - name: MINIO_SECURE
              valueFrom:
                configMapKeyRef:
                  name: fms-config
                  key: MINIO_SECURE
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fms-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fms-secrets
                  key: MINIO_SECRET_KEY
            resources:
              requests:
                memory: "2Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "2000m"
          restartPolicy: OnFailure
